### ISSUE TITLE
version inconsistencies

### ISSUE THREAD

**Issue by sporritt** [jsplumb-demonstrations/draggable-connections#2]
package.json lists "5.0.0" as the `browser-ui` version, but "^5.0.0" for `connector-bezier`. This will result in a mismatch between the versions installed, and the Bezier connector won't be available to the jsPlumb instance. 

originally reported on [jsplumb](https://github.com/jsplumb/jsplumb/issues/1131)

**Comment by sporritt** [comment]
should be fixed now.

**Comment by xu4wang** [comment]
Did a quick test, the issue is still there.  The changes I made:

In demo.js,  I save the instance in window.j.

```
   jsPlumbBrowserUI.ready(function () {

        var instance = window.j = jsPlumbBrowserUI.newInstance({
            dragOptions: { cursor: 'pointer', zIndex: 2000 },
            paintStyle: { stroke: '#666' },
            endpointHoverStyle: { fill: "orange" },
            hoverPaintStyle: { stroke: "orange" },
            endpointStyle: { width: 20, height: 16, stroke: '#666' },
            endpoint: "Rectangle",
            anchors: ["Top", "Top"],
            container: canvas
        });


```

and 
1. use snippets to add DIVs dynamically, 
2. connect DIVs via instance.connect

https://github.com/jsplumb/jsplumb/issues/1131#issuecomment-1145559554

**Comment by xu4wang** [comment]
> i am not at my computer but i very much doubt the issue persists. you should remove all the jsplumb stuff from node modules and reinstall.

Simon, Thanks for your quick response.  It was a clean install.. I clone this repo, and ```npm install``` inside js folder.

I believe the issue is not related to versions.  Both 5.0.0 and 5.7.1 get the same behavior.

**Comment by sporritt** [comment]
it turns out the behaviour you are referring to is not a bug; it's because the default `paintStyle` lacks a `strokeWidth` value. 

in this issue I was referring to the fact that connections between the green endpoints are currently broken in this demonstration:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/262720/171822290-208b5875-7e07-40a2-968f-1bf273463b93.png">


the cause of which is definitely the version mismatch discussed here.
